language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

sudo: false

env:
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=2.1
    - DJANGO=master

matrix:
    fast_finish: true
    include:
      - python: "3.6"
        env: DJANGO=master
      - python: "3.6"
        env: DJANGO=1.11
      - python: "3.6"
        env: DJANGO=2.0
      - python: "3.6"
        env: DJANGO=2.1
      - python: "3.3"
        env: DJANGO=1.8
      - python: "2.7"
        env: TOXENV="isort"
      - python: "2.7"
        env: TOXENV="lint"
      - python: "3.5"
        env: TOXENV="lint"
    exclude:
      - python: "2.7"
        env: DJANGO=master
      - python: "3.4"
        env: DJANGO=master

    allow_failures:
      - env: DJANGO=master

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gdal-bin

install:
    - pip install tox tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO
